name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WINDOWS_SSH_HOST }} # Endereço IP ou nome da sua máquina Windows
        username: ${{ secrets.WINDOWS_SSH_USERNAME }} # Seu nome de usuário na máquina Windows
        key: ${{ secrets.WINDOWS_SSH_KEY }} # Sua chave SSH privada (como um segredo do GitHub)
        script: |
          mkdir -p "D:\\OlimpiAtos\\Production"
          rsync -avz -e ssh . "${{ secrets.WINDOWS_SSH_USERNAME }}@${{ secrets.WINDOWS_SSH_HOST }}:D:\\OlimpiAtos\\Production"